2016-10-14 15:39:47.949 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-14 15:39:48.015 [info] <0.7.0> Application lager started on node nonode@nohost
2016-10-14 15:39:48.020 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-10-14 15:39:48.027 [info] <0.7.0> Application logger_file_backend started on node nonode@nohost
2016-10-14 15:39:48.031 [info] <0.7.0> Application yams started on node nonode@nohost
2016-10-14 15:39:56.510 [warning] <0.6.0> lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
2016-10-14 15:39:56.512 [info] <0.7.0> Application fs started on node nonode@nohost
2016-10-14 15:39:56.516 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
2016-10-14 15:41:00.813 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-14 15:41:00.852 [info] <0.7.0> Application lager started on node nonode@nohost
2016-10-14 15:41:00.854 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-10-14 15:41:00.858 [info] <0.7.0> Application logger_file_backend started on node nonode@nohost
2016-10-14 15:41:00.861 [info] <0.7.0> Application yams started on node nonode@nohost
2016-10-14 15:41:01.080 [warning] <0.6.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
2016-10-14 15:41:01.160 [info] <0.7.0> Application perf started on node nonode@nohost
2016-10-14 15:41:06.517 [info] <0.7.0> Application fs started on node nonode@nohost
2016-10-14 15:41:06.517 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
2016-10-14 15:42:16.627 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-14 15:42:16.676 [info] <0.7.0> Application lager started on node nonode@nohost
2016-10-14 15:42:16.679 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-10-14 15:42:16.682 [info] <0.7.0> Application logger_file_backend started on node nonode@nohost
2016-10-14 15:42:16.685 [info] <0.7.0> Application yams started on node nonode@nohost
2016-10-14 15:42:17.094 [warning] <0.6.0> lager_error_logger_h dropped 71 messages in the last second that exceeded the limit of 50 messages/sec
2016-10-14 15:42:17.116 [info] <0.7.0> Application perf started on node nonode@nohost
2016-10-14 15:42:21.856 [info] <0.7.0> Application fs started on node nonode@nohost
2016-10-14 15:42:21.857 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
2016-10-14 16:25:01.599 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-14 16:25:01.654 [info] <0.7.0> Application lager started on node nonode@nohost
2016-10-14 16:25:01.657 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-10-14 16:25:01.661 [info] <0.7.0> Application logger_file_backend started on node nonode@nohost
2016-10-14 16:25:01.663 [info] <0.7.0> Application yams started on node nonode@nohost
2016-10-14 16:25:07.248 [warning] <0.6.0> lager_error_logger_h dropped 70 messages in the last second that exceeded the limit of 50 messages/sec
2016-10-14 16:25:07.248 [info] <0.7.0> Application fs started on node nonode@nohost
2016-10-14 16:25:07.248 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
2016-10-14 20:47:32.456 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-14 20:47:32.518 [info] <0.7.0> Application lager started on node nonode@nohost
2016-10-14 20:47:32.521 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-10-14 20:47:32.525 [info] <0.7.0> Application logger_file_backend started on node nonode@nohost
2016-10-14 20:47:32.528 [info] <0.7.0> Application yams started on node nonode@nohost
2016-10-14 20:47:32.744 [info] <0.7.0> Application perf started on node nonode@nohost
2016-10-14 20:47:48.795 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.199.0> exit with reason normal in context child_terminated
2016-10-14 20:47:48.845 [info] <0.7.0> Application lager started on node nonode@nohost
2016-10-14 20:47:48.853 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-10-14 20:47:48.865 [info] <0.7.0> Application logger_file_backend started on node nonode@nohost
2016-10-14 20:47:48.870 [info] <0.7.0> Application yams started on node nonode@nohost
2016-10-14 20:47:49.005 [warning] <0.6.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
2016-10-14 20:47:49.194 [info] <0.7.0> Application perf started on node nonode@nohost
2016-10-14 20:47:50.987 [info] <0.7.0> Application fs started on node nonode@nohost
2016-10-14 20:47:50.987 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
2016-10-15 09:56:46.321 [error] <0.5428.0> gen_server <0.5428.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20179,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.323 [error] <0.5430.0> gen_server <0.5430.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20177,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.324 [error] <0.5428.0> CRASH REPORT Process <0.5428.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20179,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.324 [error] <0.5430.0> CRASH REPORT Process <0.5430.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20177,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.325 [error] <0.5427.0> gen_server <0.5427.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20180,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.326 [error] <0.5427.0> CRASH REPORT Process <0.5427.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20180,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.326 [error] <0.5434.0> gen_server <0.5434.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20175,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.327 [error] <0.5434.0> CRASH REPORT Process <0.5434.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20175,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.328 [error] <0.5436.0> gen_server <0.5436.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20172,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.328 [error] <0.5436.0> CRASH REPORT Process <0.5436.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20172,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.329 [error] <0.5429.0> gen_server <0.5429.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20178,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.331 [error] <0.5431.0> gen_server <0.5431.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20176,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.331 [error] <0.5429.0> CRASH REPORT Process <0.5429.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20178,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.331 [error] <0.5431.0> CRASH REPORT Process <0.5431.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20176,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.332 [error] <0.5432.0> gen_server <0.5432.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20173,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.333 [error] <0.5435.0> gen_server <0.5435.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20174,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.333 [error] <0.5432.0> CRASH REPORT Process <0.5432.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20173,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.334 [error] <0.5435.0> CRASH REPORT Process <0.5435.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20174,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.334 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5428.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20179,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.335 [error] <0.5433.0> gen_server <0.5433.0> terminated with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20171,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576
2016-10-15 09:56:46.335 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5430.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20177,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.335 [error] <0.5433.0> CRASH REPORT Process <0.5433.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20171,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in gen_server:terminate/7 line 826
2016-10-15 09:56:46.336 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5427.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20180,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.336 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5434.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20175,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.336 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5436.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20172,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.336 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5429.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20178,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.336 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5431.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20176,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.337 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5432.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20173,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.337 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5435.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20174,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 09:56:46.337 [error] <0.5426.0> Supervisor {<0.5426.0>,poolboy_sup} had child undefined started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5433.0> exit with reason no function clause matching 'Elixir.Postgrex.Protocol':handle_msg(#{'__struct__' => 'Elixir.Postgrex.Protocol',buffer => nil,connection_id => 20171,null => nil,parameters => ...,...}, #{mode => transaction,notify => #Fun<Elixir.Postgrex.Protocol.19.103984769>,sync => sync}, {msg_error,[{severity,<<"FATAL">>},{code,<<"57P01">>},{message,<<"terminating connection due to ad...">>},...]}) line 1576 in context child_terminated
2016-10-15 13:27:50.972 [error] <0.938.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.943.0> exit with reason normal in context child_terminated
2016-10-15 13:27:51.091 [info] <0.7.0> Application lager started on node nonode@nohost
2016-10-15 13:27:51.095 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-10-15 13:27:51.101 [info] <0.7.0> Application logger_file_backend started on node nonode@nohost
2016-10-15 13:27:51.103 [info] <0.7.0> Application yams started on node nonode@nohost
2016-10-15 13:27:54.257 [warning] <0.6.0> lager_error_logger_h dropped 19 messages in the last second that exceeded the limit of 50 messages/sec
2016-10-15 13:27:54.257 [info] <0.7.0> Application fs started on node nonode@nohost
2016-10-15 13:27:54.258 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
