2016-09-18 17:59:01.214 [error] <0.954.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.959.0> exit with reason normal in context child_terminated
2016-09-18 17:59:01.319 [info] <0.7.0> Application lager started on node nonode@nohost
2016-09-18 17:59:01.323 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-09-18 17:59:01.531 [info] <0.7.0> Application perf started on node nonode@nohost
2016-09-18 17:59:01.647 [info] <0.7.0> Application ex_unit started on node nonode@nohost
2016-09-19 23:41:26.800 [error] <0.193.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.198.0> exit with reason normal in context child_terminated
2016-09-19 23:41:26.852 [info] <0.7.0> Application lager started on node nonode@nohost
2016-09-19 23:41:26.855 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-09-19 23:41:27.001 [warning] <0.6.0> lager_error_logger_h dropped 67 messages in the last second that exceeded the limit of 50 messages/sec
2016-09-19 23:41:27.155 [info] <0.7.0> Application perf started on node nonode@nohost
2016-09-19 23:44:31.563 [info] <0.7.0> Application fs started on node nonode@nohost
2016-09-19 23:44:31.563 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
2016-09-19 23:44:33.627 [error] <0.5454.0> gen_server <0.5454.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:33.627 [error] <0.5454.0> CRASH REPORT Process <0.5454.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:34.652 [error] <0.5466.0> gen_server <0.5466.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:34.652 [error] <0.5466.0> CRASH REPORT Process <0.5466.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:35.685 [error] <0.5467.0> gen_server <0.5467.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:35.686 [error] <0.5467.0> CRASH REPORT Process <0.5467.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:36.708 [error] <0.5468.0> gen_server <0.5468.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:36.708 [error] <0.5468.0> CRASH REPORT Process <0.5468.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:37.732 [error] <0.5469.0> gen_server <0.5469.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:37.733 [error] <0.5469.0> CRASH REPORT Process <0.5469.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:38.752 [error] <0.5470.0> gen_server <0.5470.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:38.754 [error] <0.5470.0> CRASH REPORT Process <0.5470.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:39.818 [error] <0.5472.0> gen_server <0.5472.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:39.818 [error] <0.5472.0> CRASH REPORT Process <0.5472.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:40.866 [error] <0.5473.0> gen_server <0.5473.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:40.866 [error] <0.5473.0> CRASH REPORT Process <0.5473.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:41.905 [error] <0.5474.0> gen_server <0.5474.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:41.905 [error] <0.5474.0> CRASH REPORT Process <0.5474.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:42.948 [error] <0.5475.0> gen_server <0.5475.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:42.949 [error] <0.5475.0> CRASH REPORT Process <0.5475.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:43.985 [error] <0.5476.0> gen_server <0.5476.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:43.986 [error] <0.5476.0> CRASH REPORT Process <0.5476.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19096,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:45.020 [error] <0.5477.0> gen_server <0.5477.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405
2016-09-19 23:44:45.021 [error] <0.5477.0> CRASH REPORT Process <0.5477.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 19091,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"2876">>,message => <<"column r0.min_concurrency does not exist">>,pg_code => <<"42703">>,position => <<"94">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>}} in 'Elixir.Ecto.Adapters.SQL':execute_and_cache/7 line 405 in gen_server:terminate/7 line 826
2016-09-19 23:44:46.045 [error] <0.5478.0> gen_server <0.5478.0> terminated with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth/2 from 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1622
2016-09-19 23:44:46.045 [error] <0.5478.0> CRASH REPORT Process <0.5478.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,...},...},...}, #{'__struct__' => 'Elixir.Perf.Resource.State',conn => nil,error => nil,kind => ok,model => nil,...}) in gen_server:terminate/7 line 826
2016-09-19 23:45:08.814 [error] <0.193.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.198.0> exit with reason normal in context child_terminated
2016-09-19 23:45:08.866 [info] <0.7.0> Application lager started on node nonode@nohost
2016-09-19 23:45:08.869 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-09-19 23:45:09.019 [warning] <0.6.0> lager_error_logger_h dropped 67 messages in the last second that exceeded the limit of 50 messages/sec
2016-09-19 23:45:09.246 [info] <0.7.0> Application perf started on node nonode@nohost
2016-09-19 23:45:15.538 [info] <0.7.0> Application fs started on node nonode@nohost
2016-09-19 23:45:15.539 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
2016-09-19 23:45:16.526 [error] <0.5454.0> gen_server <0.5454.0> terminated with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth/2 from 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1622
2016-09-19 23:45:16.534 [error] <0.5454.0> CRASH REPORT Process <0.5454.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,...},...},...}, #{'__struct__' => 'Elixir.Perf.Resource.State',conn => nil,error => nil,kind => ok,model => nil,...}) in gen_server:terminate/7 line 826
2016-09-19 23:45:27.498 [error] <0.5479.0> gen_server <0.5479.0> terminated with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth/2 from 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1622
2016-09-19 23:45:27.498 [error] <0.5479.0> CRASH REPORT Process <0.5479.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,...},...},...}, #{'__struct__' => 'Elixir.Perf.Resource.State',conn => nil,error => nil,kind => ok,model => nil,...}) in gen_server:terminate/7 line 826
2016-09-19 23:45:49.407 [error] <0.708.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.713.0> exit with reason normal in context child_terminated
2016-09-19 23:45:49.504 [info] <0.7.0> Application lager started on node nonode@nohost
2016-09-19 23:45:49.507 [info] <0.7.0> Application getopt started on node nonode@nohost
2016-09-19 23:45:52.835 [warning] <0.6.0> lager_error_logger_h dropped 68 messages in the last second that exceeded the limit of 50 messages/sec
2016-09-19 23:45:52.836 [info] <0.7.0> Application fs started on node nonode@nohost
2016-09-19 23:45:52.836 [info] <0.7.0> Application phoenix_live_reload started on node nonode@nohost
2016-09-19 23:45:53.123 [error] <0.5962.0> gen_server <0.5962.0> terminated with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth/2 from 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1622
2016-09-19 23:45:53.135 [error] <0.5962.0> CRASH REPORT Process <0.5962.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,...},...},...}, #{'__struct__' => 'Elixir.Perf.Resource.State',conn => nil,error => nil,kind => ok,model => nil,...}) in gen_server:terminate/7 line 826
2016-09-19 23:46:04.939 [error] <0.5977.0> gen_server <0.5977.0> terminated with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth/2 from 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1622
2016-09-19 23:46:04.939 [error] <0.5977.0> CRASH REPORT Process <0.5977.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Perf.Resource.Suite':check_auth(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,...},...},...}, #{'__struct__' => 'Elixir.Perf.Resource.State',conn => nil,error => nil,kind => ok,model => nil,...}) in gen_server:terminate/7 line 826
